=== Лабораторная работа №5
*Задание:*

_Настроить таймер TIM2 аналогично системному таймеру, то есть написать программу морганиями светодиодами на плате с периодом в 0,5 секунды. По нажатию кнопки увеличивать период морганиями на 0,1 секунды._

Код программы:
----
#include "rccregisters.hpp"
#include "gpiocregisters.hpp"
#include "gpioaregisters.hpp"
#include <iostream>
#include "tim2registers.hpp"

constexpr std::uint32_t CpuClock = 8'000'000U;
auto delay_ms(std::uint32_t ButPeriod)
{
    TIM2::CR1::URS::OverflowEvent::Set();
    TIM2::PSC::Set(7999U);
    TIM2::ARR::Write(ButPeriod - 1U);
    TIM2::SR::UIF::NoInterruptPending::Set();
    TIM2::CNT::Write(0);
    TIM2::CR1::CEN::Enable::Set();
while (!TIM2::SR::UIF::NoInterruptPending::IsSet() )
{
}
    TIM2::CR1::CEN::Disable::Set();
}
int main()
{
    unsigned int ButPeriod = 100U;
    unsigned int LedsPeriod = 500U;
    unsigned int counter = 0;
    bool flag = false;
    RCC::CR::HSEON::On::Set();
while(!RCC::CR::HSERDY::Ready::IsSet())
{
}
    RCC::CFGR::SW::Hse::Set();
while(!RCC::CFGR::SWS::Hse::IsSet())
{
}
    RCC::AHB1ENR::GPIOCEN::Enable::Set();
    RCC::AHB1ENR::GPIOAEN::Enable::Set();
    GPIOC::MODER::MODER5::Output::Set();
    GPIOC::MODER::MODER13::Input::Set();
    GPIOA::MODER::MODER5::Output::Set();
    GPIOC::MODER::MODER9::Output::Set();
    GPIOC::MODER::MODER8::Output::Set();
    RCC::APB1ENR::TIM2EN::Enable::Set();
for(;;)
{
delay_ms(ButPeriod);
if(GPIOC::IDR::IDR13::Low::IsSet())
{
    LedsPeriod += 100U;
    counter = 0;
}
    counter = counter + ButPeriod;
    if(counter >= LedsPeriod)
{
if(!flag)
{
    GPIOC::BSRR::BS8::High::Write();
    GPIOC::BSRR::BS9::High::Write();
    GPIOC::BSRR::BS5::High::Write();
    GPIOA::BSRR::BS5::High::Write();
flag = true;
}
else
{
    GPIOC::BSRR::BR9::Low::Write();
    GPIOC::BSRR::BR8::Low::Write();
    GPIOC::BSRR::BR5::Low::Write();
    GPIOA::BSRR::BR5::Low::Write();
flag = false;
}
    counter = 0;
}
}
return 1;
}
----

_Результат данного кода заключается в том, что изначально светодиоды моргают на плате с периодом 0,5 секунды, а при каждом нажатии кнопки период моргания увеличивается на 0,1 секунды._

*Описание действий:*

Сначала подали тактирование на модуль таймера. Работаем мы от _HSE_, *8 МГц*. Для того,чтобы таймер заработал, его нужно подключить к системе тактирования (шина _APB1)_.
----
RCC::APB1ENR::TIM2EN::Enable::Set();
----
Установим источник генерации прерываний по событию переполнений по событию переполнение с помощью бита _URS_ в регистре _CR1_
----
TIM2::CR1::URS::OverflowEvent::Set();
----
Установим значение до которого счётчик будет считать в регистре перезагрузке _ARR_ и зададим делитель частоты (для _HSE_ - *7999*):
----
TIM2::PSC::Set(7999U);
TIM2::ARR::Write(ButPeriod - 1U);
----
Скинем флаг генерации прерывания _UIF_ по событию в регистре _SR_:
----
TIM2::SR::UIF::NoInterruptPending::Set();
----
Установим начальное значение счётчика в значение *0* в регистре _CNT_:
----
TIM2::CNT::Write(0);
----
Запустим счетчик с помощью бита _EN_ в регистре _CR1_:
----
TIM2::CR1::CEN::Enable::Set();
----
Дождемся, пока не будет установлен флаг генерации прерывания по событию _UIF_ в регистре _SR_:
----
while (!TIM2::SR::UIF::NoInterruptPending::IsSet() )
{
}
----

После того,как флаг установится - останавливаем счетчик, сбрасывая бит _EN_ в регистре _CR1_
----
TIM2::CR1::CEN::Disable::Set();
----